spring.application.name=cultural-events-api

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/swagger
logging.level.org.springframework.security=DEBUG

springdoc.swagger-ui.oauth.client-id=culturalevents-api
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.scopes=openid,profile,email

app.keycloak.auth-url=${KEYCLOAK_PUBLIC_URL}/realms/culturalevents/protocol/openid-connect/auth
app.keycloak.token-url=${KEYCLOAK_PUBLIC_URL}/realms/culturalevents/protocol/openid-connect/token
springdoc.swagger-ui.oauth2-redirect-url=${API_PUBLIC_URL}/swagger-ui/oauth2-redirect.html

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
